/**
 * generated by Xtext
 */
package imt.simhya.language.validation;

import imt.simhya.language.validation.AbstractMpmValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MpmValidator extends AbstractMpmValidator {
}
