/*
* generated by Xtext
*/
package imt.simhya.language.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import imt.simhya.language.services.MarkovPopulationModelsGrammarAccess;

public class MarkovPopulationModelsParser extends AbstractContentAssistParser {
	
	@Inject
	private MarkovPopulationModelsGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected imt.simhya.language.ui.contentassist.antlr.internal.InternalMarkovPopulationModelsParser createParser() {
		imt.simhya.language.ui.contentassist.antlr.internal.InternalMarkovPopulationModelsParser result = new imt.simhya.language.ui.contentassist.antlr.internal.InternalMarkovPopulationModelsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getConstantAccess().getAlternatives(), "rule__Constant__Alternatives");
					put(grammarAccess.getExprAccess().getAlternatives(), "rule__Expr__Alternatives");
					put(grammarAccess.getExprovaAccess().getAlternatives(), "rule__Exprova__Alternatives");
					put(grammarAccess.getInitAccess().getAlternatives(), "rule__Init__Alternatives");
					put(grammarAccess.getGeneratorAccess().getAlternatives_2(), "rule__Generator__Alternatives_2");
					put(grammarAccess.getLoc_tranAccess().getAlternatives(), "rule__Loc_tran__Alternatives");
					put(grammarAccess.getState_condAccess().getAlternatives(), "rule__State_cond__Alternatives");
					put(grammarAccess.getState_refAccess().getAlternatives(), "rule__State_ref__Alternatives");
					put(grammarAccess.getAction_condAccess().getAlternatives(), "rule__Action_cond__Alternatives");
					put(grammarAccess.getConstantAccess().getGroup_0(), "rule__Constant__Group_0__0");
					put(grammarAccess.getConstantAccess().getGroup_1(), "rule__Constant__Group_1__0");
					put(grammarAccess.getParamsAccess().getGroup(), "rule__Params__Group__0");
					put(grammarAccess.getParamsAccess().getGroup_2(), "rule__Params__Group_2__0");
					put(grammarAccess.getActual_parametersAccess().getGroup(), "rule__Actual_parameters__Group__0");
					put(grammarAccess.getActual_parametersAccess().getGroup_2(), "rule__Actual_parameters__Group_2__0");
					put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
					put(grammarAccess.getAgentAccess().getGroup(), "rule__Agent__Group__0");
					put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getActionAccess().getGroup_3(), "rule__Action__Group_3__0");
					put(grammarAccess.getActionAccess().getGroup_3_2(), "rule__Action__Group_3_2__0");
					put(grammarAccess.getExprovaAccess().getGroup_1(), "rule__Exprova__Group_1__0");
					put(grammarAccess.getExprovaAccess().getGroup_2(), "rule__Exprova__Group_2__0");
					put(grammarAccess.getPopulationAccess().getGroup(), "rule__Population__Group__0");
					put(grammarAccess.getPopulationAccess().getGroup_6(), "rule__Population__Group_6__0");
					put(grammarAccess.getInitAccess().getGroup_0(), "rule__Init__Group_0__0");
					put(grammarAccess.getInitAccess().getGroup_0_4(), "rule__Init__Group_0_4__0");
					put(grammarAccess.getInitAccess().getGroup_0_6(), "rule__Init__Group_0_6__0");
					put(grammarAccess.getInitAccess().getGroup_1(), "rule__Init__Group_1__0");
					put(grammarAccess.getInitAccess().getGroup_1_4(), "rule__Init__Group_1_4__0");
					put(grammarAccess.getStateInitAccess().getGroup(), "rule__StateInit__Group__0");
					put(grammarAccess.getGl_tranAccess().getGroup(), "rule__Gl_tran__Group__0");
					put(grammarAccess.getGl_tranAccess().getGroup_2(), "rule__Gl_tran__Group_2__0");
					put(grammarAccess.getGl_tranAccess().getGroup_2_2(), "rule__Gl_tran__Group_2_2__0");
					put(grammarAccess.getGl_tranAccess().getGroup_5(), "rule__Gl_tran__Group_5__0");
					put(grammarAccess.getGeneratorAccess().getGroup(), "rule__Generator__Group__0");
					put(grammarAccess.getGeneratorAccess().getGroup_2_1(), "rule__Generator__Group_2_1__0");
					put(grammarAccess.getGeneratorAccess().getGroup_2_2(), "rule__Generator__Group_2_2__0");
					put(grammarAccess.getGeneratorAccess().getGroup_2_2_2(), "rule__Generator__Group_2_2_2__0");
					put(grammarAccess.getLoc_tranAccess().getGroup_0(), "rule__Loc_tran__Group_0__0");
					put(grammarAccess.getLoc_tranAccess().getGroup_1(), "rule__Loc_tran__Group_1__0");
					put(grammarAccess.getLoc_tranAccess().getGroup_2(), "rule__Loc_tran__Group_2__0");
					put(grammarAccess.getState_condAccess().getGroup_0(), "rule__State_cond__Group_0__0");
					put(grammarAccess.getState_condAccess().getGroup_1(), "rule__State_cond__Group_1__0");
					put(grammarAccess.getState_condAccess().getGroup_1_1(), "rule__State_cond__Group_1_1__0");
					put(grammarAccess.getState_refAccess().getGroup_0(), "rule__State_ref__Group_0__0");
					put(grammarAccess.getState_refAccess().getGroup_0_2(), "rule__State_ref__Group_0_2__0");
					put(grammarAccess.getState_refAccess().getGroup_1(), "rule__State_ref__Group_1__0");
					put(grammarAccess.getState_refAccess().getGroup_1_4(), "rule__State_ref__Group_1_4__0");
					put(grammarAccess.getState_refAccess().getGroup_2(), "rule__State_ref__Group_2__0");
					put(grammarAccess.getState_refAccess().getGroup_2_6(), "rule__State_ref__Group_2_6__0");
					put(grammarAccess.getAction_condAccess().getGroup_0(), "rule__Action_cond__Group_0__0");
					put(grammarAccess.getMainAccess().getConstDefAssignment_0(), "rule__Main__ConstDefAssignment_0");
					put(grammarAccess.getMainAccess().getLocationDefAssignment_1(), "rule__Main__LocationDefAssignment_1");
					put(grammarAccess.getMainAccess().getAgentDefAssignment_2(), "rule__Main__AgentDefAssignment_2");
					put(grammarAccess.getMainAccess().getPopulationDefAssignment_3(), "rule__Main__PopulationDefAssignment_3");
					put(grammarAccess.getConstantAccess().getNameAssignment_0_1(), "rule__Constant__NameAssignment_0_1");
					put(grammarAccess.getConstantAccess().getConstINTAssignment_0_3(), "rule__Constant__ConstINTAssignment_0_3");
					put(grammarAccess.getConstantAccess().getNameAssignment_1_1(), "rule__Constant__NameAssignment_1_1");
					put(grammarAccess.getConstantAccess().getConstFLOATAssignment_1_3(), "rule__Constant__ConstFLOATAssignment_1_3");
					put(grammarAccess.getExprAccess().getConstRefAssignment_0(), "rule__Expr__ConstRefAssignment_0");
					put(grammarAccess.getExprAccess().getConstFLOATAssignment_1(), "rule__Expr__ConstFLOATAssignment_1");
					put(grammarAccess.getExprAccess().getConstINTAssignment_2(), "rule__Expr__ConstINTAssignment_2");
					put(grammarAccess.getParamsAccess().getParamsAssignment_1(), "rule__Params__ParamsAssignment_1");
					put(grammarAccess.getParamsAccess().getParamsAssignment_2_1(), "rule__Params__ParamsAssignment_2_1");
					put(grammarAccess.getActual_parametersAccess().getActualParamsAssignment_1(), "rule__Actual_parameters__ActualParamsAssignment_1");
					put(grammarAccess.getActual_parametersAccess().getActualParamsAssignment_2_1(), "rule__Actual_parameters__ActualParamsAssignment_2_1");
					put(grammarAccess.getLocationAccess().getNameAssignment_1(), "rule__Location__NameAssignment_1");
					put(grammarAccess.getLocationAccess().getParamListAssignment_2(), "rule__Location__ParamListAssignment_2");
					put(grammarAccess.getLocationAccess().getActAssignment_5(), "rule__Location__ActAssignment_5");
					put(grammarAccess.getLocationAccess().getSAssignment_6(), "rule__Location__SAssignment_6");
					put(grammarAccess.getAgentAccess().getNameAssignment_1(), "rule__Agent__NameAssignment_1");
					put(grammarAccess.getAgentAccess().getParamListAssignment_2(), "rule__Agent__ParamListAssignment_2");
					put(grammarAccess.getAgentAccess().getActAssignment_5(), "rule__Agent__ActAssignment_5");
					put(grammarAccess.getAgentAccess().getSAssignment_6(), "rule__Agent__SAssignment_6");
					put(grammarAccess.getLabelAccess().getNameAssignment(), "rule__Label__NameAssignment");
					put(grammarAccess.getStateAccess().getNameAssignment_1(), "rule__State__NameAssignment_1");
					put(grammarAccess.getStateAccess().getParamListAssignment_2(), "rule__State__ParamListAssignment_2");
					put(grammarAccess.getStateAccess().getSpontaneousActAssignment_4(), "rule__State__SpontaneousActAssignment_4");
					put(grammarAccess.getActionAccess().getActRefAssignment_0(), "rule__Action__ActRefAssignment_0");
					put(grammarAccess.getActionAccess().getStateRefAssignment_2(), "rule__Action__StateRefAssignment_2");
					put(grammarAccess.getActionAccess().getParamsAssignment_3_1(), "rule__Action__ParamsAssignment_3_1");
					put(grammarAccess.getActionAccess().getParamsAssignment_3_2_1(), "rule__Action__ParamsAssignment_3_2_1");
					put(grammarAccess.getActionAccess().getLocalRateAssignment_5(), "rule__Action__LocalRateAssignment_5");
					put(grammarAccess.getExprovaAccess().getExprAssignment_0(), "rule__Exprova__ExprAssignment_0");
					put(grammarAccess.getExprovaAccess().getExprAssignment_1_0(), "rule__Exprova__ExprAssignment_1_0");
					put(grammarAccess.getExprovaAccess().getNumAssignment_1_2(), "rule__Exprova__NumAssignment_1_2");
					put(grammarAccess.getExprovaAccess().getExprAssignment_2_0(), "rule__Exprova__ExprAssignment_2_0");
					put(grammarAccess.getExprovaAccess().getNumAssignment_2_2(), "rule__Exprova__NumAssignment_2_2");
					put(grammarAccess.getExprovaAccess().getNumAssignment_3(), "rule__Exprova__NumAssignment_3");
					put(grammarAccess.getPopulationAccess().getNameAssignment_1(), "rule__Population__NameAssignment_1");
					put(grammarAccess.getPopulationAccess().getParamListAssignment_2(), "rule__Population__ParamListAssignment_2");
					put(grammarAccess.getPopulationAccess().getAgentsAssignment_5(), "rule__Population__AgentsAssignment_5");
					put(grammarAccess.getPopulationAccess().getAgentsAssignment_6_1(), "rule__Population__AgentsAssignment_6_1");
					put(grammarAccess.getPopulationAccess().getTranAssignment_7(), "rule__Population__TranAssignment_7");
					put(grammarAccess.getInitAccess().getAgentRefAssignment_0_0(), "rule__Init__AgentRefAssignment_0_0");
					put(grammarAccess.getInitAccess().getActualParametersAssignment_0_1(), "rule__Init__ActualParametersAssignment_0_1");
					put(grammarAccess.getInitAccess().getStatesAssignment_0_3(), "rule__Init__StatesAssignment_0_3");
					put(grammarAccess.getInitAccess().getStatesAssignment_0_4_1(), "rule__Init__StatesAssignment_0_4_1");
					put(grammarAccess.getInitAccess().getLocRefAssignment_0_6_1(), "rule__Init__LocRefAssignment_0_6_1");
					put(grammarAccess.getInitAccess().getPopRefAssignment_1_0(), "rule__Init__PopRefAssignment_1_0");
					put(grammarAccess.getInitAccess().getCardAssignment_1_2(), "rule__Init__CardAssignment_1_2");
					put(grammarAccess.getInitAccess().getLocRefAssignment_1_4_1(), "rule__Init__LocRefAssignment_1_4_1");
					put(grammarAccess.getStateInitAccess().getStateRefAssignment_0(), "rule__StateInit__StateRefAssignment_0");
					put(grammarAccess.getStateInitAccess().getCardAssignment_2(), "rule__StateInit__CardAssignment_2");
					put(grammarAccess.getGl_tranAccess().getNameAssignment_1(), "rule__Gl_tran__NameAssignment_1");
					put(grammarAccess.getGl_tranAccess().getGeneratorsAssignment_2_1(), "rule__Gl_tran__GeneratorsAssignment_2_1");
					put(grammarAccess.getGl_tranAccess().getGeneratorsAssignment_2_2_1(), "rule__Gl_tran__GeneratorsAssignment_2_2_1");
					put(grammarAccess.getGl_tranAccess().getLTranAssignment_4(), "rule__Gl_tran__LTranAssignment_4");
					put(grammarAccess.getGl_tranAccess().getLTranAssignment_5_1(), "rule__Gl_tran__LTranAssignment_5_1");
					put(grammarAccess.getGl_tranAccess().getRateAssignment_7(), "rule__Gl_tran__RateAssignment_7");
					put(grammarAccess.getGeneratorAccess().getNameAssignment_0(), "rule__Generator__NameAssignment_0");
					put(grammarAccess.getGeneratorAccess().getValueEXPAssignment_2_0(), "rule__Generator__ValueEXPAssignment_2_0");
					put(grammarAccess.getGeneratorAccess().getValueMinAssignment_2_1_0(), "rule__Generator__ValueMinAssignment_2_1_0");
					put(grammarAccess.getGeneratorAccess().getValueMaxAssignment_2_1_2(), "rule__Generator__ValueMaxAssignment_2_1_2");
					put(grammarAccess.getGeneratorAccess().getValueListAssignment_2_2_1(), "rule__Generator__ValueListAssignment_2_2_1");
					put(grammarAccess.getGeneratorAccess().getValueListAssignment_2_2_2_1(), "rule__Generator__ValueListAssignment_2_2_2_1");
					put(grammarAccess.getLoc_tranAccess().getStateRefAssignment_0_1(), "rule__Loc_tran__StateRefAssignment_0_1");
					put(grammarAccess.getLoc_tranAccess().getStateRefAssignment_1_1(), "rule__Loc_tran__StateRefAssignment_1_1");
					put(grammarAccess.getLoc_tranAccess().getSCondAssignment_2_0(), "rule__Loc_tran__SCondAssignment_2_0");
					put(grammarAccess.getLoc_tranAccess().getACondAssignment_2_2(), "rule__Loc_tran__ACondAssignment_2_2");
					put(grammarAccess.getState_condAccess().getStateRefAssignment_1_0(), "rule__State_cond__StateRefAssignment_1_0");
					put(grammarAccess.getState_condAccess().getStateRefAssignment_1_1_1(), "rule__State_cond__StateRefAssignment_1_1_1");
					put(grammarAccess.getState_refAccess().getStateRefAssignment_0_0(), "rule__State_ref__StateRefAssignment_0_0");
					put(grammarAccess.getState_refAccess().getActualParametersAssignment_0_1(), "rule__State_ref__ActualParametersAssignment_0_1");
					put(grammarAccess.getState_refAccess().getLocRefAssignment_0_2_1(), "rule__State_ref__LocRefAssignment_0_2_1");
					put(grammarAccess.getState_refAccess().getAgentStateRefAssignment_1_0(), "rule__State_ref__AgentStateRefAssignment_1_0");
					put(grammarAccess.getState_refAccess().getStateRefAssignment_1_2(), "rule__State_ref__StateRefAssignment_1_2");
					put(grammarAccess.getState_refAccess().getActualParametersAssignment_1_3(), "rule__State_ref__ActualParametersAssignment_1_3");
					put(grammarAccess.getState_refAccess().getLocRefAssignment_1_4_1(), "rule__State_ref__LocRefAssignment_1_4_1");
					put(grammarAccess.getState_refAccess().getPopAgentStateRefAssignment_2_0(), "rule__State_ref__PopAgentStateRefAssignment_2_0");
					put(grammarAccess.getState_refAccess().getAgentStateRefAssignment_2_2(), "rule__State_ref__AgentStateRefAssignment_2_2");
					put(grammarAccess.getState_refAccess().getStateRefAssignment_2_4(), "rule__State_ref__StateRefAssignment_2_4");
					put(grammarAccess.getState_refAccess().getActualParametersAssignment_2_5(), "rule__State_ref__ActualParametersAssignment_2_5");
					put(grammarAccess.getState_refAccess().getLocRefAssignment_2_6_1(), "rule__State_ref__LocRefAssignment_2_6_1");
					put(grammarAccess.getAction_condAccess().getActionRefAssignment_1(), "rule__Action_cond__ActionRefAssignment_1");
					put(grammarAccess.getMainAccess().getUnorderedGroup(), "rule__Main__UnorderedGroup");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			imt.simhya.language.ui.contentassist.antlr.internal.InternalMarkovPopulationModelsParser typedParser = (imt.simhya.language.ui.contentassist.antlr.internal.InternalMarkovPopulationModelsParser) parser;
			typedParser.entryRulemain();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MarkovPopulationModelsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MarkovPopulationModelsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
