/**
 * generated by Xtext
 */
package imt.simhya.language.ui.contentassist;

import imt.simhya.language.ui.contentassist.AbstractMpmProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MpmProposalProvider extends AbstractMpmProposalProvider {
}
