/*
* generated by Xtext
*/
package imt.simhya.language;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MarkovPopulationModelsUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return imt.simhya.language.ui.internal.MarkovPopulationModelsActivator.getInstance().getInjector("imt.simhya.language.MarkovPopulationModels");
	}
	
}
