/*
* generated by Xtext
*/
package imt.simhya.language;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MpmUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return imt.simhya.language.ui.internal.MpmActivator.getInstance().getInjector("imt.simhya.language.Mpm");
	}
	
}
