/*
* generated by Xtext
*/
package imt.simhya.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import imt.simhya.language.services.MarkovPopulationModelsGrammarAccess;

public class MarkovPopulationModelsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MarkovPopulationModelsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected imt.simhya.language.parser.antlr.internal.InternalMarkovPopulationModelsParser createParser(XtextTokenStream stream) {
		return new imt.simhya.language.parser.antlr.internal.InternalMarkovPopulationModelsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "main";
	}
	
	public MarkovPopulationModelsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MarkovPopulationModelsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
