/*
* generated by Xtext
*/
package imt.simhya.language.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MarkovPopulationModelsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("imt/simhya/language/parser/antlr/internal/InternalMarkovPopulationModels.tokens");
	}
}
