/*
* generated by Xtext
*/
package imt.simhya.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import imt.simhya.language.services.MpmGrammarAccess;

public class MpmParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MpmGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected imt.simhya.language.parser.antlr.internal.InternalMpmParser createParser(XtextTokenStream stream) {
		return new imt.simhya.language.parser.antlr.internal.InternalMpmParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public MpmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MpmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
