/*
 * generated by Xtext
 */
package imt.simhya.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MarkovPopulationModelsUiModule extends imt.simhya.language.ui.AbstractMarkovPopulationModelsUiModule {
	public MarkovPopulationModelsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
