/*
 * generated by Xtext
 */
package imt.simhya.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MpmUiModule extends imt.simhya.language.ui.AbstractMpmUiModule {
	public MpmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
