/*
 * generated by Xtext
 */
package imt.simhya.language.ui.contentassist

import imt.simhya.language.ui.contentassist.AbstractMarkovPopulationModelsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MarkovPopulationModelsProposalProvider extends AbstractMarkovPopulationModelsProposalProvider {
}
