/*
* generated by Xtext
*/
package imt.simhya.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MarkovPopulationModelsStandaloneSetup extends MarkovPopulationModelsStandaloneSetupGenerated{

	public static void doSetup() {
		new MarkovPopulationModelsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

