/*
 * generated by Xtext
 */
package imt.simhya.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MpmRuntimeModule extends imt.simhya.language.AbstractMpmRuntimeModule {

}
