/*
* generated by Xtext
*/
package imt.simhya.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MpmStandaloneSetup extends MpmStandaloneSetupGenerated{

	public static void doSetup() {
		new MpmStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

